theme: jekyll-theme-minimal
name: Alexander Ek
title: Alexander Ek
description: Computer Scientist - Online Combinatorial Optimization

test


testing
github_username:  aekh
plugins:
  - jekyll-seo-tag
